# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://mazhuang.org
date_format: "ordinal"
title: Xpress Song
subtitle: "相由心生"
description: "Grow up"
keywords: xpress song
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/xpressSong/xpressSong.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Xpress Song
organization: I2finance, Inc.
organization_url: http://www.i2finance.net/
location: Beijing, China
email: q13859601@hotmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: xpressSong
douban_username: 
facebook_username: 
weibo_username: 
zhihu_username: 
twitter_username: 

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: 
disqus_username: xpressSong

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java]
skill_mobile_app_keywords: [Android]
skill_windows_keywords: [Java]
