permalink: /:year-:month-:day/:title/

highlighter: rouge
markdown: kramdown


kramdown:
  input:         GFM
  auto_ids:      true
  auto_id_prefix: 'id-'
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   true

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         2
    coderay_bold_every:        10
    coderay_css:               style

# markdown: redcarpet
# redcarpet:
#   extensions: [
#    "no_intra_emphasis"
#    ,"fenced_code_blocks"
#    ,"autolink"
#    ,"tables"
#    ,"strikethrough"
#    ,"superscript"
#    ,"with_toc_data"
#    ,"footnotes"
#    ,"highlight"
#    ,"underline"
#    ,"quote"
#    ,"lax_spacing"
#    ,"prettify"
# #   ,"html_toc"
#   ]


paginate: 10
paginate_path: ":num"
baseurl: ""



title: "XpressSong"
email: "707339962@qq.com"
description: "随心而行"
github_username:  "xpressSong"
swiftype_searchId: "xkJt5q5xLmkzMaYvyuQa"
disqus_shortname: "xpresssong"



url: "http://xpressSong.github.io"
imgrepo: "http://xpressSong.github.io/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

