# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://songxp.top
date_format: "ordinal"
title: Andy
subtitle: "南飞的驴"
description: "Keep change."
keywords: Andy
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/songxianpeng/songxianpeng.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Andy
organization: Alibaba, Inc.
organization_url: http://www.alibaba.com/
location: Hangzhou, China
email: songxianpeng@hotmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /tools/
    label: 工具

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #

highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    tools:
        output: true
        permalink: /tools/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: songxianpeng
douban_username: 
facebook_username: 
weibo_username: 
zhihu_username: 
twitter_username: 

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus,gitalk
# comments_provider: disqus
comments_provider: 
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
disqus_username: xpressSong


# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java]
skill_mobile_app_keywords: [Android]
skill_windows_keywords: [Java]
