# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://songxp.top
date_format: "ordinal"
title: Andy
subtitle: "南飞的驴"
description: "Keep change."
keywords: Andy
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/songxianpeng/songxianpeng.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Andy
organization: Alibaba, Inc.
organization_url: http://www.alibaba.com/
location: Hangzhou, China
email: songxianpeng@hotmail.com
